[features]
seeds = false
skip-lint = false

[programs.localnet]
carbon_credit_exchange = "G1oyFNSMSHRBPG6LWWpAMhJJNf23HWjNpq8FALJSUqs3"

[programs.devnet]
carbon_credit_exchange = "G1oyFNSMSHRBPG6LWWpAMhJJNf23HWjNpq8FALJSUqs3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"